### ISSUE TITLE
Evaluation Documentation

### ISSUE THREAD

**Issue by DrX3D** [KhronosGroup/3DC-Certification#16]
Please include a README that describes how to use the evaluation software, especially for non-python developers. For example, on my local machine, I get a message "No module names 'skimage'". I am not sure what to do about that.

**Comment by UX3D-becher** [comment]
added a README in 7c6f19c744fb7192fa342250f8d9b4674ee6bc45

**Comment by DrX3D** [comment]
I appreciate the new documentation. Now it seems I have a chance...

However, following the instructions, the code runs and produces an JSON file containing an empty array ('{}') and a PDF that just has a header. There is no error / warning message about being unable to open a file.

This is running on Windows 7 (not that Homebrew isn't for Windows) with Python V3.8.10 (latest full build that runs on Win7). All of the packages were installed. I tried several different versions of paths and all produced the same results.

The Reference images are stored in ../models and ./models (and I tried a few others). All image files are of the form 'rr-*.png'.

The Certificant files are in a directory with the filename form 'c-*.png'.

**Comment by UX3D-becher** [comment]
We have updated the README with more info about how to install Python3 on windows and listed some typical gotchas that might be the cause of your problems.

When cloning the repo and executing the evaluation script, the `--rep` option is not needed, the reference images are found automatically. 

We also have tried it on Windows 10 but it should work on other Windows versions as well.

**Comment by DrX3D** [comment]
Documentation is great. I can run the software and produce results.
