### ISSUE TITLE
Evaluation Software Running

### ISSUE THREAD

**Issue by DrX3D** [KhronosGroup/3DC-Certification#17]
Reading the evaluation software, it appears that there are some assumptions made about the rendered file names. It looks as if the software processes all rendered images in one go. Is it possible to change this so that the reference and test images are provided from the command line. This also impacts another issue discussing output files and formats.

**Comment by UX3D-nopper** [comment]
The name of the files are defined in the validation document.
However, we will add some documentation here:
https://github.com/KhronosGroup/3DC-Certification/issues/16
