### ISSUE TITLE
Evaluation Software Output

### ISSUE THREAD

**Issue by DrX3D** [KhronosGroup/3DC-Certification#18]
It appears that the evaluation software generates a human-readable, styled report. Is it reasonable to have JSON or other computer-friendly output format(s)? Can the output format and file be specified on the command line to facilitate batch processing?

**Comment by UX3D-nopper** [comment]
We we add a JSON dump in parallel to the PDF.

**Comment by UX3D-becher** [comment]
#15 now generates a JSON report alongside the PDF report (commit a26df12)

**Comment by DrX3D** [comment]
Wonderful, it works.
