### ISSUE TITLE
Code Sometimes Generates Error

### ISSUE THREAD

**Issue by DrX3D** [KhronosGroup/3DC-Certification#19]
Sometimes when I run the program everything works correctly and runs to completion. Other times I get an error. 

```
C:\...\evaluation>python evaluation.py  --rep .. --name 12 --output ..\Results\12 ..\12  1>..\Results\12.log
Traceback (most recent call last):
  File "evaluation.py", line 148, in <module>
    reference_image, candidate_image = normalize_images(reference_image, candidate_image)
  File "evaluation.py", line 113, in normalize_images
    print(f"??  Resizing {candidate_path} from {candidate.shape[:2]} to {reference.shape[:2]}")
  File "C:\Applications\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>
```

There is only the "gather_image:..." output line when the code fails. When it succeeds. there are also 3 data lines for each commerce model by camera position.

**Comment by DrX3D** [comment]
Assigned to @UX3D-nopper for re-assignment or resolution.

**Comment by DrX3D** [comment]
I think I have found and fixed the problem. I'll post a PR later today.

**Comment by DrX3D** [comment]
The problem was 2 unrecognized characters on line 112. The branch [test2-20210914](https://github.com/KhronosGroup/3DC-Certification/tree/test2-20210914) fixes those by replacing them with a [newline]. Please check to make sure that this is all good.

**Comment by UX3D-becher** [comment]
merged into evaluation
